version: '3.9'

services:
  web:
    build:
      context: ./backend-workout-tracker
    ports:
      - "8000:8000"
    volumes:
      - ./backend-workout-tracker:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    # depends_on:
    #   - db

  server:
    build:
      context: ./frontend-workout-tracker
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: yourusername
#       POSTGRES_PASSWORD: yourpassword
#       POSTGRES_DB: yourdatabase

# volumes:
#   postgres_data:
