version: '3.9'

services:
  backend:
    container_name: backend-service
    build:
      context: ./backend-workout-tracker
    ports:
      - "8000:8000"
    volumes:
      - ./backend-workout-tracker:/app
    environment:
      - SECRET_KEY=dadsjkfhasiduflajkbsdfoiahedfasdlkfnalsjd
      - NODE_ENV=development
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: frontend-service
    build:
      context: ./client-workout-tracker
    ports:
      - "3000:3000"
    volumes:
      - ./client-workout-tracker:/app
      - /app/node_modules
      - ./client-workout-tracker/.next:/app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
