version: '3.9'

services:
  backend:
    build:
      context: ./backend-workout-tracker
    ports:
      - "8000:8000"
    volumes:
      - ./backend-workout-tracker:/app
    environment:
      - SECRET_KEY=dadsjkfhasiduflajkbsdfoiahedfasdlkfnalsjd
      - NODE_ENV=development # Ensure NODE_ENV is set for backend if needed

  frontend:
    build:
      context: ./client-workout-tracker
    ports:
      - "3000:3000"
    volumes:
      - ./client-workout-tracker:/app
    environment:
      - NODE_ENV=development

  # Uncomment the following lines if you want to add a PostgreSQL database
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: yourusername
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_DB: yourdatabase

# volumes:
#   postgres_data:
